version: "3.8"

services:
  db:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_HOST_PORT}:${DB_CONTAINER_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: