ALTER TABLE order_items ALTER COLUMN quantity DROP NOT NULL;
ALTER TABLE orders ALTER COLUMN order_date DROP NOT NULL;
ALTER TABLE products ALTER COLUMN name DROP NOT NULL;
ALTER TABLE products ALTER COLUMN price DROP NOT NULL;
ALTER TABLE products ALTER COLUMN stock_quantity DROP NOT NULL;
ALTER TABLE products_shelves ALTER COLUMN is_primary DROP NOT NULL;
ALTER TABLE shelves ALTER COLUMN name DROP NOT NULL;
