ALTER TABLE order_items ALTER COLUMN quantity SET NOT NULL;
ALTER TABLE orders ALTER COLUMN order_date SET NOT NULL;
ALTER TABLE products ALTER COLUMN name SET NOT NULL;
ALTER TABLE products ALTER COLUMN price SET NOT NULL;
ALTER TABLE products ALTER COLUMN stock_quantity SET NOT NULL;
ALTER TABLE products_shelves ALTER COLUMN is_primary SET NOT NULL;
ALTER TABLE shelves ALTER COLUMN name SET NOT NULL;