// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"time"
)

type Order struct {
	ID        int64     `json:"id"`
	OrderDate time.Time `json:"order_date"`
}

type OrderItem struct {
	ID        int64 `json:"id"`
	OrderID   int64 `json:"order_id"`
	ProductID int64 `json:"product_id"`
	Quantity  int32 `json:"quantity"`
}

type Product struct {
	ID            int64  `json:"id"`
	Name          string `json:"name"`
	Price         int32  `json:"price"`
	StockQuantity int32  `json:"stock_quantity"`
}

type ProductsShelf struct {
	ID        int64 `json:"id"`
	ProductID int64 `json:"product_id"`
	ShelvesID int64 `json:"shelves_id"`
	IsPrimary bool  `json:"is_primary"`
}

type Shelf struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}
