// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	GetOrderInfo(ctx context.Context, dollar_1 []int64) ([]GetOrderInfoRow, error)
}

var _ Querier = (*Queries)(nil)
